CREATE TABLE account (
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type          VARCHAR(32)   NOT NULL,
    owner_user_id BIGINT        NULL REFERENCES app_user (id),
    balance       NUMERIC(19,4) NOT NULL DEFAULT 0,
    version       BIGINT        NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_account_type CHECK (type IN ('USER_WALLET', 'SYSTEM_FUNDING', 'SYSTEM_PAYOUT')),
    CONSTRAINT ck_wallet_owner CHECK ((type = 'USER_WALLET') = (owner_user_id IS NOT NULL)),
    CONSTRAINT ck_wallet_non_negative CHECK (type <> 'USER_WALLET' OR balance >= 0)
);

-- One wallet per user. System accounts are exempt because their owner_user_id is null,
-- and a partial index skips null rows.
CREATE UNIQUE INDEX uq_wallet_owner ON account (owner_user_id) WHERE type = 'USER_WALLET';

-- The outside world. SYSTEM_FUNDING goes negative as money enters the system, so
-- abs(its balance) is the total ever deposited.
INSERT INTO account (id, type, owner_user_id, balance)
VALUES (1, 'SYSTEM_FUNDING', NULL, 0),
       (2, 'SYSTEM_PAYOUT',  NULL, 0);
SELECT setval(pg_get_serial_sequence('account', 'id'), 2);

CREATE TABLE ledger_transaction (
    id                      BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id               UUID        NOT NULL UNIQUE,
    type                    VARCHAR(16) NOT NULL,
    reverses_transaction_id BIGINT      NULL UNIQUE REFERENCES ledger_transaction (id),
    initiated_by_user_id    BIGINT      NOT NULL REFERENCES app_user (id),
    description             VARCHAR(255),
    created_at              TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT ck_transaction_type CHECK (type IN ('DEPOSIT', 'WITHDRAWAL', 'TRANSFER', 'REVERSAL')),
    CONSTRAINT ck_reversal_link CHECK ((type = 'REVERSAL') = (reverses_transaction_id IS NOT NULL))
);

CREATE TABLE ledger_entry (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id BIGINT        NOT NULL REFERENCES ledger_transaction (id),
    account_id     BIGINT        NOT NULL REFERENCES account (id),
    amount         NUMERIC(19,4) NOT NULL,
    created_at     TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_entry_amount_non_zero CHECK (amount <> 0)
);

CREATE INDEX idx_entry_transaction ON ledger_entry (transaction_id);
CREATE INDEX idx_entry_account_created ON ledger_entry (account_id, created_at DESC, id DESC);

-- Guarantee 2: the ledger is append-only. Corrections are posted as reversing
-- transactions, never as edits. A future migration that must touch this table has to
-- drop and recreate this trigger explicitly.
CREATE OR REPLACE FUNCTION reject_ledger_mutation() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION 'ledger_entry is append-only; % is not allowed', TG_OP
        USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_ledger_entry_immutable
    BEFORE UPDATE OR DELETE ON ledger_entry
    FOR EACH ROW EXECUTE FUNCTION reject_ledger_mutation();

-- Guarantee 3: every transaction balances. A normal constraint fires per row and would
-- reject the first entry of every pair, so this one is deferred to COMMIT, by which time
-- both sides of the entry exist.
CREATE OR REPLACE FUNCTION assert_transaction_balanced() RETURNS trigger AS $$
DECLARE
    total NUMERIC(19,4);
BEGIN
    SELECT COALESCE(SUM(amount), 0) INTO total
      FROM ledger_entry
     WHERE transaction_id = NEW.transaction_id;

    IF total <> 0 THEN
        RAISE EXCEPTION 'Unbalanced transaction %: entries sum to %', NEW.transaction_id, total
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE CONSTRAINT TRIGGER trg_transaction_balanced
    AFTER INSERT ON ledger_entry
    DEFERRABLE INITIALLY DEFERRED
    FOR EACH ROW EXECUTE FUNCTION assert_transaction_balanced();
