-- The row is written in two moments: the key is claimed as the operation starts, and the
-- response is recorded as it finishes. So response_status and response_body are nullable, and a
-- row with a null body means an operation still in flight — which is exactly what the
-- concurrent-duplicate case needs to detect.
CREATE TABLE idempotency_key (
    id              BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT        NOT NULL REFERENCES app_user (id),
    idem_key        VARCHAR(64)   NOT NULL,
    endpoint        VARCHAR(64)   NOT NULL,
    request_hash    VARCHAR(64)   NOT NULL,
    response_status INT           NULL,
    -- VARCHAR, not TEXT: Hibernate maps String to VARCHAR and ddl-auto=validate compares the
    -- JDBC type. A transaction response is a few hundred bytes, so 4096 is generous.
    response_body   VARCHAR(4096) NULL,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    -- Scoped per user, so two clients choosing the same key never collide.
    CONSTRAINT uq_idempotency_user_key UNIQUE (user_id, idem_key)
);

CREATE TABLE audit_log (
    id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT        NULL REFERENCES app_user (id),
    action     VARCHAR(64)   NOT NULL,
    detail     VARCHAR(1000),
    outcome    VARCHAR(16)   NOT NULL,
    created_at TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT ck_audit_outcome CHECK (outcome IN ('SUCCESS', 'FAILURE'))
);

CREATE INDEX idx_audit_user_created ON audit_log (user_id, created_at DESC);
