-- The dual-write problem: a money transaction and a Kafka publish cannot share one commit. This
-- table is the fix -- the event is written inside the same transaction as the ledger write
-- (LedgerPostingService.post()), and a separate relay publishes it later. idx_outbox_pending is a
-- partial index: once an event is published it never needs to be found by this query again, so
-- there is no reason to keep indexing it.
CREATE TABLE outbox_event (
    id             BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aggregate_type VARCHAR(32) NOT NULL,
    aggregate_id   BIGINT      NOT NULL,
    event_type     VARCHAR(64) NOT NULL,
    payload        JSONB       NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at   TIMESTAMPTZ NULL,
    attempts       INT         NOT NULL DEFAULT 0
);

CREATE INDEX idx_outbox_pending ON outbox_event (id) WHERE published_at IS NULL;

-- notification.event_id is what makes NotificationConsumer idempotent: Kafka delivery is
-- at-least-once, so the same event_id can arrive twice, and the UNIQUE constraint turns a
-- redelivery into a no-op instead of a duplicate row.
CREATE TABLE notification (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT       NOT NULL REFERENCES app_user (id),
    type       VARCHAR(64)  NOT NULL,
    message    VARCHAR(500) NOT NULL,
    event_id   UUID         NOT NULL UNIQUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
